apiVersion: v1
kind: Pod
metadata:
  name: limits-pod

spec:
  restartPolicy: OnFailure
  containers:
  - name: main
    image: polinux/stress
    resources:
      limits:
        cpu: 400m
        memory: 1Gi
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes","500M","--vm-hang","1"]
    #args: ["--vm", "1", "--vm-bytes","2G","--vm-hang","1"]