apiVersion: v1
kind: Pod
metadata:
  name: request-pod
spec:
  containers:
  - image: busybox
    command: ["dd", "if=/dev/zero", "of=/dev/null"]
    name: main
    resources:
      request:
        cpu: 400m
        memmory: 2G