apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  selector:
    app: photo-view   # ← Pod 라벨과 동일하게 맞춤
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer   # 클라우드에서 외부 노출 원하면 추가
